/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Helper.connectionHelper;
import Model.logSession;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Dashboard extends javax.swing.JFrame {

    String ID = logSession.getNama_user();

    Connection con;
    Statement stm;
    ResultSet rs;

    /**
     * Creates new form Dashbord
     */
    public Dashboard() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        viewpane.setEnabled(false);
        viewpane.setVisible(false);
        log1.setEnabled(false);
        log1.setVisible(false);
        userName.setText(logSession.getUsername());

        kasMasuk();
         kasKeluar();
         getTotalKas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kasMasukTxt = new javax.swing.JLabel();
        vKasKeluar = new javax.swing.JLabel();
        vSaldo = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        log2 = new javax.swing.JLabel();
        log1 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JLabel();
        btnKasmasuk = new javax.swing.JLabel();
        btnKaskeluar = new javax.swing.JLabel();
        X = new javax.swing.JLabel();
        viewpane = new javax.swing.JPanel();
        viewlogout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(kasMasukTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 70, 20));
        getContentPane().add(vKasKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 80, 20));
        getContentPane().add(vSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 274, 80, 30));

        userName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 50, 20));

        log2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log2MouseClicked(evt);
            }
        });
        getContentPane().add(log2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 40));

        log1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log1MouseClicked(evt);
            }
        });
        getContentPane().add(log1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 40));

        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });
        getContentPane().add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 178, 145, 40));

        btnKasmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKasmasukMouseClicked(evt);
            }
        });
        getContentPane().add(btnKasmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 219, 145, 40));

        btnKaskeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKaskeluarMouseClicked(evt);
            }
        });
        getContentPane().add(btnKaskeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 145, 40));

        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
        });
        getContentPane().add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 0, 38, 38));

        viewpane.setBackground(new java.awt.Color(249, 249, 249));
        viewpane.setLayout(null);

        viewlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logout copy.png"))); // NOI18N
        viewpane.add(viewlogout);
        viewlogout.setBounds(0, 0, 105, 40);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        viewpane.add(jLabel3);
        jLabel3.setBounds(0, 0, 105, 40);

        getContentPane().add(viewpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 105, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mockup dashboard copy.JPG"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void getUsername() {
        try {
            Connection con = connectionHelper.getConnection();
            Statement stm = con.createStatement();
            String sql = "SELECT Username FROM tb_login WHERE ";
            rs = stm.executeQuery(sql);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void kasMasuk() {
        try {
            Connection con = connectionHelper.getConnection();
            Statement stm = con.createStatement();
            String sql = "SELECT sum(jumlah) as jumlah from tb_masuk";

            rs = stm.executeQuery(sql);
            while (rs.next()) {
                kasMasukTxt.setText(rs.getString("jumlah"));
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
     private void kasKeluar() {
        try {
            Connection con = connectionHelper.getConnection();
            Statement stm = con.createStatement();
            String sql = "SELECT sum(jumlah) as jumlah from tb_keluar";

            rs = stm.executeQuery(sql);
            while (rs.next()) {
                vKasKeluar.setText(rs.getString("jumlah"));
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
     
     private void getTotalKas(){
         try {
             int kasMasuk = Integer.parseInt(kasMasukTxt.getText());
         int kasKeluar = Integer.parseInt(vKasKeluar.getText());
         int total = (kasMasuk - kasKeluar);
         vSaldo.setText(String.valueOf(total));
         } catch (Exception e) {
             System.out.println(e);
         }
     }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = 1 + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void log1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log1MouseClicked
        viewpane.setEnabled(false);
        viewpane.setVisible(false);
        log1.setEnabled(false);
        log1.setVisible(false);
        log2.setEnabled(true);
        log2.setVisible(true);
    }//GEN-LAST:event_log1MouseClicked

    private void log2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log2MouseClicked
        viewpane.setEnabled(true);
        viewpane.setVisible(true);
        log1.setEnabled(true);
        log1.setVisible(true);
        log2.setEnabled(false);
        log2.setVisible(false);
    }//GEN-LAST:event_log2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnKasmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasmasukMouseClicked
        new KasMasuk().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKasmasukMouseClicked

    private void btnKaskeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKaskeluarMouseClicked
        new KasKeluar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKaskeluarMouseClicked

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        this.dispose();
    }//GEN-LAST:event_XMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel X;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnKaskeluar;
    private javax.swing.JLabel btnKasmasuk;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel kasMasukTxt;
    private javax.swing.JLabel log1;
    private javax.swing.JLabel log2;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel vKasKeluar;
    private javax.swing.JLabel vSaldo;
    private javax.swing.JLabel viewlogout;
    private javax.swing.JPanel viewpane;
    // End of variables declaration//GEN-END:variables
}
